version: '3.7'

services:
  pgsql:
    image: ankane/pgvector:latest
    ports:
      - '${DB_PORT}:5432'
    container_name: Postgres
    volumes:
      - ./volumes/pg-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DATABASE}
    restart: always

volumes:
  pg-data:
