from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS "aerich" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(100) NOT NULL,
    "content" JSONB NOT NULL
);
CREATE TABLE IF NOT EXISTS "aids" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "alcoolismo" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "antirretroviral" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "bac_escarro1" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "bac_escarro2" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "bacilosc_2mes" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "bacilosc_6mes" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "banco_metadados" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome_tabela" VARCHAR(5000) NOT NULL,
    "descricao_tabela" TEXT NOT NULL,
    "categorias" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "benef_governo" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "cultura_escarro" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "diabetes" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "doenca_mental" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "droga_ilicita" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "extra_pulm1" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "extra_pulm2" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "forma" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "hiv" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "idade" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "imigrante" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "municipio_resid" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "outra_doenca" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "ppl" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "pop_sit_rua" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "prof_saude" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "raca" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "raio_x" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "sexo" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "situacao_encerra" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "tabagismo" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "teste_molec" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "teste_rapido_tb" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "teste_sensibilidade" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "tipo_entrada" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "uf" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "nome" VARCHAR(5000) NOT NULL,
    "criado_em" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "fatos" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "data" DATE NOT NULL,
    "ano_nasc" VARCHAR(50) NOT NULL,
    "criado_em" TIMESTAMPTZ   DEFAULT CURRENT_TIMESTAMP,
    "aids_id" BIGINT REFERENCES "aids" ("id") ON DELETE CASCADE,
    "alcoolismo_id" BIGINT REFERENCES "alcoolismo" ("id") ON DELETE CASCADE,
    "antirretroviral_id" BIGINT REFERENCES "antirretroviral" ("id") ON DELETE CASCADE,
    "bac_escarro1_id" BIGINT REFERENCES "bac_escarro1" ("id") ON DELETE CASCADE,
    "bac_escarro2_id" BIGINT REFERENCES "bac_escarro2" ("id") ON DELETE CASCADE,
    "benef_governo_id" BIGINT REFERENCES "benef_governo" ("id") ON DELETE CASCADE,
    "cultura_escarro_id" BIGINT REFERENCES "cultura_escarro" ("id") ON DELETE CASCADE,
    "diabetes_id" BIGINT REFERENCES "diabetes" ("id") ON DELETE CASCADE,
    "doenca_mental_id" BIGINT REFERENCES "doenca_mental" ("id") ON DELETE CASCADE,
    "droga_ilicita_id" BIGINT REFERENCES "droga_ilicita" ("id") ON DELETE CASCADE,
    "extra_pulm1_id" BIGINT REFERENCES "extra_pulm1" ("id") ON DELETE CASCADE,
    "extra_pulm2_id" BIGINT REFERENCES "extra_pulm2" ("id") ON DELETE CASCADE,
    "forma_id" BIGINT REFERENCES "forma" ("id") ON DELETE CASCADE,
    "hiv_id" BIGINT REFERENCES "hiv" ("id") ON DELETE CASCADE,
    "imigrante_id" BIGINT REFERENCES "imigrante" ("id") ON DELETE CASCADE,
    "municipio_resid_id" BIGINT REFERENCES "municipio_resid" ("id") ON DELETE CASCADE,
    "outra_doenca_id" BIGINT REFERENCES "outra_doenca" ("id") ON DELETE CASCADE,
    "pop_sit_rua_id" BIGINT REFERENCES "pop_sit_rua" ("id") ON DELETE CASCADE,
    "ppl_id" BIGINT REFERENCES "ppl" ("id") ON DELETE CASCADE,
    "prof_saude_id" BIGINT REFERENCES "prof_saude" ("id") ON DELETE CASCADE,
    "raca_id" BIGINT REFERENCES "raca" ("id") ON DELETE CASCADE,
    "sexo_id" BIGINT REFERENCES "sexo" ("id") ON DELETE CASCADE,
    "tabagismo_id" BIGINT REFERENCES "tabagismo" ("id") ON DELETE CASCADE,
    "teste_rapido_tb_id" BIGINT REFERENCES "teste_rapido_tb" ("id") ON DELETE CASCADE,
    "teste_sensibilidade_id" BIGINT REFERENCES "teste_sensibilidade" ("id") ON DELETE CASCADE,
    "tipo_entrada_id" BIGINT REFERENCES "tipo_entrada" ("id") ON DELETE CASCADE,
    "uf_id" BIGINT REFERENCES "uf" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "menssagens_chat" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "chat_id" BIGINT NOT NULL,
    "sender" VARCHAR(10) NOT NULL,
    "content" TEXT NOT NULL,
    "criado_em" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

"""



async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """
