from tortoise.models import Model
from tortoise import fields

class FactTable(Model):
    id = fields.BigIntField(primary_key=True)
    regiao_notif_id = fields.ForeignKeyField("models.RegiaoNotif", related_name="facts", null=True)
    uf_notif_id = fields.ForeignKeyField("models.UFNotif", related_name="facts", null=True)
    municipio_notif_id = fields.ForeignKeyField("models.MunicipioNotif", related_name="facts", null=True)
    capital_notif_id = fields.ForeignKeyField("models.CapitalNotif", related_name="facts", null=True)
    macrorreg_notif_id = fields.ForeignKeyField("models.MacrorregNotif", related_name="facts", null=True)
    microrreg_notif_id = fields.ForeignKeyField("models.MicrorregNotif", related_name="facts", null=True)
    reg_metrop_notif_id = fields.ForeignKeyField("models.RegMetropNotif", related_name="facts", null=True)
    territ_cidadania_notif_id = fields.ForeignKeyField("models.TerritCidadaniaNotif", related_name="facts", null=True)
    mesorregiao_notif_id = fields.ForeignKeyField("models.MesorregiaoNotif", related_name="facts", null=True)
    regiao_saude_notif_id = fields.ForeignKeyField("models.RegiaoSaudeNotif", related_name="facts", null=True)
    amazonia_legal_notif_id = fields.ForeignKeyField("models.AmazoniaLegalNotif", related_name="facts", null=True)
    semiarido_notif_id = fields.ForeignKeyField("models.SemiaridoNotif", related_name="facts", null=True)
    faixa_fronteira_notif_id = fields.ForeignKeyField("models.FaixaFronteiraNotif", related_name="facts", null=True)
    zona_fronteira_notif_id = fields.ForeignKeyField("models.ZonaFronteiraNotif", related_name="facts", null=True)
    mun_extrema_pobreza_notif_id = fields.ForeignKeyField("models.MunExtremaPobrezaNotif", related_name="facts", null=True)
    uf_resid_id = fields.ForeignKeyField("models.UFResid", related_name="facts", null=True)
    regiao_resid_id = fields.ForeignKeyField("models.RegiaoResidencia", related_name="facts", null=True)
    municipio_resid_id = fields.ForeignKeyField("models.MunicipioResid", related_name="facts", null=True)
    capital_resid_id = fields.ForeignKeyField("models.CapitalResid", related_name="facts", null=True)
    regiao_saude_resid_id = fields.ForeignKeyField("models.RegiaoSaudeResid", related_name="facts", null=True)
    macro_reg_saude_resid_id = fields.ForeignKeyField("models.MacroRegSaudeResid", related_name="facts", null=True)
    micro_reg_saude_resid_id = fields.ForeignKeyField("models.MicroRegSaudeResid", related_name="facts", null=True)
    reg_metrop_resid_id = fields.ForeignKeyField("models.RegMetropResid", related_name="facts", null=True)
    territ_cidadania_resid_id = fields.ForeignKeyField("models.TerritCidadaniaResid", related_name="facts", null=True)
    meso_regiao_pndr_resid_id = fields.ForeignKeyField("models.MesoRegiaopPNDRResid", related_name="facts", null=True)
    amazonia_legal_resid_id = fields.ForeignKeyField("models.AmazoniaLegalResid", related_name="facts", null=True)
    semiarido_resid_id = fields.ForeignKeyField("models.SemiaridoResid", related_name="facts", null=True)
    faixa_front_resid_id = fields.ForeignKeyField("models.FaixaFrontResid", related_name="facts", null=True)
    zona_front_resid_id = fields.ForeignKeyField("models.ZonaFrontResid", related_name="facts", null=True)
    mun_extrema_pobr_resid_id = fields.ForeignKeyField("models.MunExtremaPobrResid", related_name="facts", null=True)
    zona_resid_id = fields.ForeignKeyField("models.ZonaResid", related_name="facts", null=True)
    fx_etaria_id = fields.ForeignKeyField("models.FxEtaria", related_name="facts", null=True)
    fx_etaria7_id = fields.ForeignKeyField("models.FxEtaria7", related_name="facts", null=True)
    fx_etaria13_id = fields.ForeignKeyField("models.FxEtaria13", related_name="facts", null=True)
    ppl_id = fields.ForeignKeyField("models.PPL", related_name="facts", null=True)
    raca_id = fields.ForeignKeyField("models.Raca", related_name="facts", null=True)
    sexo_id = fields.ForeignKeyField("models.Sexo", related_name="facts", null=True)
    tipo_entrada_id = fields.ForeignKeyField("models.TipoEntrada", related_name="facts", null=True)
    institucionalizado_id = fields.ForeignKeyField("models.Institucionalizado", related_name="facts", null=True)
    pop_sit_rua_id = fields.ForeignKeyField("models.PopSitRua", related_name="facts", null=True)
    imigrante_id = fields.ForeignKeyField("models.Imigrante", related_name="facts", null=True)
    prof_saude_id = fields.ForeignKeyField("models.ProfSaude", related_name="facts", null=True)
    benef_governo_id = fields.ForeignKeyField("models.BenefGoverno", related_name="facts", null=True)
    forma_id = fields.ForeignKeyField("models.Forma", related_name="facts", null=True)
    extra_pulm1_id = fields.ForeignKeyField("models.ExtraPulm1", related_name="facts", null=True)
    extra_pulm2_id = fields.ForeignKeyField("models.ExtraPulm2", related_name="facts", null=True)
    aids_id = fields.ForeignKeyField("models.Aids", related_name="facts", null=True)
    alcoolismo_id = fields.ForeignKeyField("models.Alcoolismo", related_name="facts", null=True)
    diabetes_id = fields.ForeignKeyField("models.Diabetes", related_name="facts", null=True)
    doenca_mental_id = fields.ForeignKeyField("models.DoencaMental", related_name="facts", null=True)
    drogas_ilicitas_id = fields.ForeignKeyField("models.DrogasIlicitas", related_name="facts", null=True)
    tabagismo_id = fields.ForeignKeyField("models.Tabagismo", related_name="facts", null=True)
    outra_doenca_id = fields.ForeignKeyField("models.OutraDoenca", related_name="facts", null=True)
    confirmacao_laboratorial_id = fields.ForeignKeyField("models.ConfirmacaoLaboratorial", related_name="facts", null=True)
    bac_escarro1_id = fields.ForeignKeyField("models.BacEscarro1", related_name="facts", null=True)
    bac_escarro2_id = fields.ForeignKeyField("models.BacEscarro2", related_name="facts", null=True)
    cultura_escarro_id = fields.ForeignKeyField("models.CulturaEscarro", related_name="facts", null=True)
    teste_rapido_tb_id = fields.ForeignKeyField("models.TesteRapidoTB", related_name="facts", null=True)
    teste_sensibilidade_id = fields.ForeignKeyField("models.TesteSensibilidade", related_name="facts", null=True)
    hiv_id = fields.ForeignKeyField("models.HIV", related_name="facts", null=True)
    antirretroviral_id = fields.ForeignKeyField("models.Antirretroviral", related_name="facts", null=True)
    tdo_realizado_id = fields.ForeignKeyField("models.TDORealizado", related_name="facts", null=True)
    bacilosc_2mes_id = fields.ForeignKeyField("models.Bacilosc2Mes", related_name="facts", null=True)
    bacilosc_6mes_id = fields.ForeignKeyField("models.Bacilosc6Mes", related_name="facts", null=True)
    situacao_encerra_id = fields.ForeignKeyField("models.SituacaoEncerra", related_name="facts", null=True)
    criado_em = fields.DatetimeField(auto_now_add=True, null=True)

    class Meta:
        table = "fact_table"

    class Meta:
        table = "fact_table"
